baseURL = 'http://localhost:1313/'
languageCode = 'es-es'
title = 'Practicando con Hugo'
theme = ["themes/hello-friend-ng"]

[params]
backgroundImage = "/images/Fondo.jpg"

[[Menu]]
[[menu.main]]
name="Lenguaje"
identifier="Lenguaje"
url="/Lenguaje/"
weight=4

[[menu.main]]
name="Hobbies"
identifier="Hobbies"
url="/Hobbies/"
weight=3

[[menu.main]]
name="Markdown"
identifier="Markdown"
url="/Markdown/"
weight=2

[[menu.main]]
name="Presentación"
identifier="Presentacion"
url="/Presentacion/"
weight=1



