baseURL = 'https://s-anime.github.io/PracticaHugo/'
languageCode = 'es-es'
title = 'Practicando con Hugo'
publishDir = "docs"
theme = "/hello-friend-ng"
[params]
backgroundImage = "/images/Fondo.jpg"

[[Menu]]
[[menu.main]]
name="Lenguaje"
identifier="Lenguaje"
url="/Lenguaje/"
weight=4

[[menu.main]]
name="Hobbies"
identifier="Hobbies"
url="/Hobbies/"
weight=3

[[menu.main]]
name="Markdown"
identifier="Markdown"
url="/Markdown/"
weight=2

[[menu.main]]
name="Presentación"
identifier="Presentacion"
url="/Presentacion/"
weight=1



